spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_onboarding    //employee_onboarding is the name of mysql database
    username: root
    password: "***"   //change to your db password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "*"
logging:
  level:
    root: INFO
  file:
    name:logs/application.log
server:
  port: 8082
